browser=chromium
headless=true
url=https://supportdesk.atpl.corp/

//Admin_user_creds
Admin_username=pwadmin@yopmail.com
password=ASDF@123a

//Agent_user_creds
Agent_username1 =pwagentone@yopmail.com
Agent_username2 =pwagenttwo@yopmail.com
Agent_username3 =PWAgentThree@yopmail.com
Agent_username4 =pwagentfour@yopmail.com
Agent_username5=pwagentfive@yopmail.com

//user_creds
username1 = pwuserone@yopmail.com






